In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,5,6,7,"prince",34.55,True]

In [5]:
a1 = np.array(l1)

In [7]:
a1  #converted to a higher order

array(['4', '5', '6', '7', 'prince', '34.55', 'True'], dtype='<U32')

In [9]:
a2 = np.array([[1,2,3],[4,5,6]])

In [10]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [12]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [13]:
a1.ndim

1

In [14]:
a2.ndim

2

In [15]:
a3.ndim

3

In [16]:
a1.size

7

In [17]:
a2.size

6

In [18]:
a3.size

9

In [19]:
a1.shape

(7,)

In [20]:
a2.shape

(2, 3)

In [21]:
a3.shape

(1, 3, 3)

In [22]:
np.random.randint(2,5)

4

In [23]:
np.random.randint(2,50,(3,4))

array([[35, 39, 28, 46],
       [39, 14,  3,  9],
       [48, 41, 42, 37]])

In [24]:
np.random.randint(2,50,(2,3,4))

array([[[44, 38, 26,  9],
        [ 5,  6, 38, 48],
        [13, 21, 21, 48]],

       [[ 3, 47, 23, 32],
        [37, 30,  5, 14],
        [15, 37, 47, 22]]])

In [25]:
np.random.rand(2,3)

array([[0.62886383, 0.46833582, 0.66306144],
       [0.76833435, 0.76280264, 0.1431566 ]])

In [28]:
a4 = np.random.randn(4,4) #normalized data

In [29]:
a4

array([[-0.28526008, -0.35426128, -0.81327274,  0.17280307],
       [-2.24551885,  0.96388204, -0.41633426,  1.337783  ],
       [-0.2655662 , -1.02226625, -0.69539362, -1.39823431],
       [ 0.97062732,  1.47518626,  0.24392632, -0.34783667]])

In [30]:
a4.reshape(2,8)

array([[-0.28526008, -0.35426128, -0.81327274,  0.17280307, -2.24551885,
         0.96388204, -0.41633426,  1.337783  ],
       [-0.2655662 , -1.02226625, -0.69539362, -1.39823431,  0.97062732,
         1.47518626,  0.24392632, -0.34783667]])

In [31]:
a4.reshape(8,2)

array([[-0.28526008, -0.35426128],
       [-0.81327274,  0.17280307],
       [-2.24551885,  0.96388204],
       [-0.41633426,  1.337783  ],
       [-0.2655662 , -1.02226625],
       [-0.69539362, -1.39823431],
       [ 0.97062732,  1.47518626],
       [ 0.24392632, -0.34783667]])

In [32]:
a4.reshape(2,-1)

array([[-0.28526008, -0.35426128, -0.81327274,  0.17280307, -2.24551885,
         0.96388204, -0.41633426,  1.337783  ],
       [-0.2655662 , -1.02226625, -0.69539362, -1.39823431,  0.97062732,
         1.47518626,  0.24392632, -0.34783667]])

In [33]:
a4.reshape(8,-6864)

array([[-0.28526008, -0.35426128],
       [-0.81327274,  0.17280307],
       [-2.24551885,  0.96388204],
       [-0.41633426,  1.337783  ],
       [-0.2655662 , -1.02226625],
       [-0.69539362, -1.39823431],
       [ 0.97062732,  1.47518626],
       [ 0.24392632, -0.34783667]])

In [34]:
a4.reshape(2,2,4)

array([[[-0.28526008, -0.35426128, -0.81327274,  0.17280307],
        [-2.24551885,  0.96388204, -0.41633426,  1.337783  ]],

       [[-0.2655662 , -1.02226625, -0.69539362, -1.39823431],
        [ 0.97062732,  1.47518626,  0.24392632, -0.34783667]]])

In [35]:
a4.reshape(1,1,1,1,1,2,2,4)

array([[[[[[[[-0.28526008, -0.35426128, -0.81327274,  0.17280307],
             [-2.24551885,  0.96388204, -0.41633426,  1.337783  ]],

            [[-0.2655662 , -1.02226625, -0.69539362, -1.39823431],
             [ 0.97062732,  1.47518626,  0.24392632, -0.34783667]]]]]]]])

In [36]:
a1

array(['4', '5', '6', '7', 'prince', '34.55', 'True'], dtype='<U32')

In [37]:
a1[0]

'4'

In [38]:
a1[2:6]

array(['6', '7', 'prince', '34.55'], dtype='<U32')

In [39]:
a1[2:6:2]

array(['6', 'prince'], dtype='<U32')

In [40]:
a1[::-1]

array(['True', '34.55', 'prince', '7', '6', '5', '4'], dtype='<U32')

In [41]:
a1[::]

array(['4', '5', '6', '7', 'prince', '34.55', 'True'], dtype='<U32')

In [42]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a2[0]

array([1, 2, 3])

In [44]:
a2[1]

array([4, 5, 6])

In [47]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [48]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [50]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [52]:
a5= np.random.randint(2,90,(6,5))

In [53]:
a5

array([[13, 38, 39, 89, 21],
       [58, 40, 64, 80, 25],
       [62, 66, 38, 61, 58],
       [ 6, 82,  9, 76, 28],
       [ 2, 52, 41, 66, 73],
       [60,  8, 20, 48, 11]])

In [55]:
a5[a5>40]

array([89, 58, 64, 80, 62, 66, 61, 58, 82, 76, 52, 41, 66, 73, 60, 48])

In [56]:
a5

array([[13, 38, 39, 89, 21],
       [58, 40, 64, 80, 25],
       [62, 66, 38, 61, 58],
       [ 6, 82,  9, 76, 28],
       [ 2, 52, 41, 66, 73],
       [60,  8, 20, 48, 11]])

In [57]:
a5[0][1]=00

In [58]:
a5

array([[13,  0, 39, 89, 21],
       [58, 40, 64, 80, 25],
       [62, 66, 38, 61, 58],
       [ 6, 82,  9, 76, 28],
       [ 2, 52, 41, 66, 73],
       [60,  8, 20, 48, 11]])

In [59]:
a6= np.random.randint(0,3,[3,3])

In [60]:
a6

array([[2, 2, 2],
       [1, 0, 1],
       [2, 1, 2]])

In [61]:
a7 = np.random.randint(0,3,(3,3))

In [62]:
a7

array([[1, 0, 2],
       [0, 0, 1],
       [1, 0, 1]])

In [63]:
a6*a7

array([[2, 0, 4],
       [0, 0, 1],
       [2, 0, 2]])

In [64]:
a6@a7

array([[4, 0, 8],
       [2, 0, 3],
       [4, 0, 7]])

In [65]:
a6.dot(a7)

array([[4, 0, 8],
       [2, 0, 3],
       [4, 0, 7]])

In [66]:
a6+100

array([[102, 102, 102],
       [101, 100, 101],
       [102, 101, 102]])

In [67]:
a6*2

array([[4, 4, 4],
       [2, 0, 2],
       [4, 2, 4]])

In [68]:
a6/0

C:\Users\Prince\AppData\Local\Temp\ipykernel_9164\1058679823.py:1: RuntimeWarning: divide by zero encountered in divide
  a6/0
C:\Users\Prince\AppData\Local\Temp\ipykernel_9164\1058679823.py:1: RuntimeWarning: invalid value encountered in divide
  a6/0


array([[inf, inf, inf],
       [inf, nan, inf],
       [inf, inf, inf]])

In [69]:
a6**3

array([[8, 8, 8],
       [1, 0, 1],
       [8, 1, 8]], dtype=int32)

In [70]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
a8 = np.zeros((4,4))

In [72]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
a9 = np.ones((4,5))

In [74]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
a9 + 10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [77]:
a9 + np.array([1,2,3,4,8])  #brodcasting operation on rows

array([[2., 3., 4., 5., 9.],
       [2., 3., 4., 5., 9.],
       [2., 3., 4., 5., 9.],
       [2., 3., 4., 5., 9.]])

In [80]:
a9 + np.array([[1,2,3,9]]).T  #broadcasting operations on columns

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.],
       [10., 10., 10., 10., 10.]])

In [82]:
a5

array([[13,  0, 39, 89, 21],
       [58, 40, 64, 80, 25],
       [62, 66, 38, 61, 58],
       [ 6, 82,  9, 76, 28],
       [ 2, 52, 41, 66, 73],
       [60,  8, 20, 48, 11]])

In [81]:
np.sqrt(a5)

array([[3.60555128, 0.        , 6.244998  , 9.43398113, 4.58257569],
       [7.61577311, 6.32455532, 8.        , 8.94427191, 5.        ],
       [7.87400787, 8.1240384 , 6.164414  , 7.81024968, 7.61577311],
       [2.44948974, 9.05538514, 3.        , 8.71779789, 5.29150262],
       [1.41421356, 7.21110255, 6.40312424, 8.1240384 , 8.54400375],
       [7.74596669, 2.82842712, 4.47213595, 6.92820323, 3.31662479]])

In [83]:
np.exp(a5)

array([[4.42413392e+05, 1.00000000e+00, 8.65934004e+16, 4.48961282e+38,
        1.31881573e+09],
       [1.54553894e+25, 2.35385267e+17, 6.23514908e+27, 5.54062238e+34,
        7.20048993e+10],
       [8.43835667e+26, 4.60718663e+28, 3.18559318e+16, 3.10429794e+26,
        1.54553894e+25],
       [4.03428793e+02, 4.09399696e+35, 8.10308393e+03, 1.01480039e+33,
        1.44625706e+12],
       [7.38905610e+00, 3.83100800e+22, 6.39843494e+17, 4.60718663e+28,
        5.05239363e+31],
       [1.14200739e+26, 2.98095799e+03, 4.85165195e+08, 7.01673591e+20,
        5.98741417e+04]])

In [84]:
np.log10(a5)

C:\Users\Prince\AppData\Local\Temp\ipykernel_9164\2832021342.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a5)


array([[1.11394335,       -inf, 1.59106461, 1.94939001, 1.32221929],
       [1.76342799, 1.60205999, 1.80617997, 1.90308999, 1.39794001],
       [1.79239169, 1.81954394, 1.5797836 , 1.78532984, 1.76342799],
       [0.77815125, 1.91381385, 0.95424251, 1.88081359, 1.44715803],
       [0.30103   , 1.71600334, 1.61278386, 1.81954394, 1.86332286],
       [1.77815125, 0.90308999, 1.30103   , 1.68124124, 1.04139269]])

In [85]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [86]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [89]:
np.linspace(2,3,num = 50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [90]:
np.linspace(2,3,num = 50, retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [91]:
np.arange(2,3,0.02040816326530612)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [92]:
np.logspace(2,4,num = 4,base = 10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [94]:
np.eye(5)  #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
import cufflinks as cf
import seaborn as sns
import pandas as pd

In [97]:
cf.go_offline()

In [100]:
df = pd.DataFrame(np.random.randn(100,3),columns= ['A','B','C'])

In [101]:
df

A         B         C
0  -1.227576 -0.451609  1.009742
1  -0.900524  3.040381 -0.392683
2  -0.606417  0.608884 -1.834663
3   0.606403 -1.788799  0.256297
4  -0.016417  2.259937  0.689385
..       ...       ...       ...
95 -1.301427  0.063610  0.566936
96 -0.236259 -0.923600 -2.012783
97  0.201222  0.156907  0.105798
98 -0.109374  0.376140  1.456997
99 -1.643198 -0.264880  1.780306

[100 rows x 3 columns]

In [102]:
df.iplot()

In [103]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [104]:
df1

0
0   96
1   86
2   71
3    8
4   64
..  ..
95  49
96  56
97  85
98  97
99  26

[100 rows x 1 columns]

In [105]:
df.iplot()

In [109]:
df

A         B         C
0  -1.227576 -0.451609  1.009742
1  -0.900524  3.040381 -0.392683
2  -0.606417  0.608884 -1.834663
3   0.606403 -1.788799  0.256297
4  -0.016417  2.259937  0.689385
..       ...       ...       ...
95 -1.301427  0.063610  0.566936
96 -0.236259 -0.923600 -2.012783
97  0.201222  0.156907  0.105798
98 -0.109374  0.376140  1.456997
99 -1.643198 -0.264880  1.780306

[100 rows x 3 columns]

In [110]:
df.iplot(x= 'A',y = 'B',mode = 'markers')

In [113]:
df2 = sns.load_dataset('titanic')

In [114]:
df2

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [115]:
df2.iplot(x = 'age',y ='fare',mode = 'markers')

In [116]:
df2.iplot(x = 'fare',y ='pclass',mode = 'markers')

In [117]:
df2.iplot(x = 'age',y ='pclass',mode = 'markers')

In [118]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [121]:
df2.iplot(kind = 'bar',x = 'sex',y = 'survived')