In [2]:
import pandas as pd

In [3]:
data = {'name':['prince','francis','annies','priya'],
        'salary':[100,200,300,400],
        'email_id':["prince.francis64",'alfrancis.fd',"anniesfrancis67","priyafrancis62"],
        'addr' :['DL','DL','DL','CA']
       }

In [36]:
df = pd.DataFrame(data)

In [31]:
df = pd.DataFrame(data,index = [0,1,2,3])

In [32]:
df

name  salary          email_id addr
0   prince     100  prince.francis64   DL
1  francis     200      alfrancis.fd   DL
2   annies     300   anniesfrancis67   DL
3    priya     400    priyafrancis62   CA

In [25]:
df.loc['prince':'annnies']

name  salary          email_id addr
prince    prince     100  prince.francis64   DL
francis  francis     200      alfrancis.fd   DL
annnies   annies     300   anniesfrancis67   DL

In [12]:
df.loc[5:6]   #loc will lookafter named indexes

name  salary         email_id addr
5  francis     200     alfrancis.fd   DL
6   annies     300  anniesfrancis67   DL

In [15]:
df.iloc[1:3]  #loc will lookafter default indexes

name  salary         email_id addr
5  francis     200     alfrancis.fd   DL
6   annies     300  anniesfrancis67   DL

In [26]:
data1 = {'pf_number':[234,232,54,5],
         'inocome_tax':[234,5,35,6643],
        'mobile_no':[232332,3535,46464,4645],
        "courses":['ds', 'bigdata', 'web dev','blockchain']
        }

In [28]:
df1 = pd.DataFrame(data1)

In [29]:
df1

pf_number  inocome_tax  mobile_no     courses
0        234          234     232332          ds
1        232            5       3535     bigdata
2         54           35      46464     web dev
3          5         6643       4645  blockchain

In [33]:
df

name  salary          email_id addr
0   prince     100  prince.francis64   DL
1  francis     200      alfrancis.fd   DL
2   annies     300   anniesfrancis67   DL
3    priya     400    priyafrancis62   CA

In [34]:
pd.concat([df,df1]) #axis = 0 vertical concatenation

name  salary          email_id addr  pf_number  inocome_tax  mobile_no  \
0   prince   100.0  prince.francis64   DL        NaN          NaN        NaN   
1  francis   200.0      alfrancis.fd   DL        NaN          NaN        NaN   
2   annies   300.0   anniesfrancis67   DL        NaN          NaN        NaN   
3    priya   400.0    priyafrancis62   CA        NaN          NaN        NaN   
0      NaN     NaN               NaN  NaN      234.0        234.0   232332.0   
1      NaN     NaN               NaN  NaN      232.0          5.0     3535.0   
2      NaN     NaN               NaN  NaN       54.0         35.0    46464.0   
3      NaN     NaN               NaN  NaN        5.0       6643.0     4645.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [35]:
pd.concat([df,df1],axis = 1)  #axis = 1 horizontal concatenation

name  salary          email_id addr  pf_number  inocome_tax  mobile_no  \
0   prince     100  prince.francis64   DL        234          234     232332   
1  francis     200      alfrancis.fd   DL        232            5       3535   
2   annies     300   anniesfrancis67   DL         54           35      46464   
3    priya     400    priyafrancis62   CA          5         6643       4645   

      courses  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [46]:
data2 = {'0':['prince','francis','annies','priya'],
        '1':[100,200,300,400],
        '2':["prince.francis64",'alfrancis.fd',"anniesfrancis67","priyafrancis62"],
        '3' :['DL','DL','DL','CA']
       }

In [47]:
data3 = {'0':[234,232,54,5],
         '1':[234,5,35,6643],
        '2':[232332,3535,46464,4645],
        "3":['ds', 'bigdata', 'web dev','blockchain']
        }

In [48]:
df2  = pd.DataFrame(data2)

In [49]:
df3  = pd.DataFrame(data3)

In [50]:
df2

0    1                 2   3
0   prince  100  prince.francis64  DL
1  francis  200      alfrancis.fd  DL
2   annies  300   anniesfrancis67  DL
3    priya  400    priyafrancis62  CA

In [51]:
df3

0     1       2           3
0  234   234  232332          ds
1  232     5    3535     bigdata
2   54    35   46464     web dev
3    5  6643    4645  blockchain

In [52]:
pd.concat([df2,df3])

0     1                 2           3
0   prince   100  prince.francis64          DL
1  francis   200      alfrancis.fd          DL
2   annies   300   anniesfrancis67          DL
3    priya   400    priyafrancis62          CA
0      234   234            232332          ds
1      232     5              3535     bigdata
2       54    35             46464     web dev
3        5  6643              4645  blockchain

In [53]:
pd.concat([df2,df3],axis = 1)

0    1                 2   3    0     1       2           3
0   prince  100  prince.francis64  DL  234   234  232332          ds
1  francis  200      alfrancis.fd  DL  232     5    3535     bigdata
2   annies  300   anniesfrancis67  DL   54    35   46464     web dev
3    priya  400    priyafrancis62  CA    5  6643    4645  blockchain

In [54]:
data4 = { 'emp_id':[101,102,103,104],
         "salary":[234,345,200,400],
         'pf' : [23,34,56,78],
    }

In [60]:
data5 = { "emp_id":[101,102,104,105],
         "mob_no":[3434,5656,767,878],
         'house_nu':[345,345,345,56]
}

In [57]:
df4 = pd.DataFrame(data4)

In [58]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [62]:
df5 =pd.DataFrame(data5)

In [63]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [64]:
pd.merge(df4,df5)

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [65]:
pd.merge(df4,df5,how = 'left')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [66]:
pd.merge(df4,df5,how = 'right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [67]:
pd.merge(df4,df5,how = 'right',on = 'emp_id')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [69]:
data6 = { 'emp_id1':[101,102,103,104],
         "salary":[234,345,200,400],
         'pf' : [23,34,56,78],
    }
data7 = { "emp_id2":[101,102,104,105],
         "mob_no":[3434,5656,767,878],
         'house_nu':[345,345,345,56]
}

In [70]:
df6 = pd.DataFrame(data6)
df7 = pd.DataFrame(data7)

In [73]:
pd.merge(df6,df7,left_on = 'emp_id1',right_on = 'emp_id2',how ='inner')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [75]:
data8 = { 'emp_id':[101,102,103,104],
         "salary":[234,345,200,400],
         'pf' : [23,34,56,78],
    }
data9 = { "emp_id":[101,102,104,105],
         "salary":[234,345,200,878],
         'house_nu':[345,345,345,56]
}

In [77]:
df8 = pd.DataFrame(data8)

In [92]:
df9 = pd.DataFrame(data9)

In [80]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [82]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56

In [83]:
pd.merge(df8,df9,on =['emp_id','salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [84]:
pd.merge(df8,df9,on =['salary'])

emp_id_x  salary  pf  emp_id_y  house_nu
0       101     234  23       101       345
1       102     345  34       102       345
2       103     200  56       104       345

In [90]:
data9 = { "emp_id":[101,102,104,105,123],
         "salary":[234,345,200,878,43],
         'house_nu':[345,345,345,56,234]
}

In [93]:
pd.merge(df8,df9)

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [105]:
data10 = { 'emp_id1':[101,102,103,104],
         "salary1":[234,345,200,400],
         'pf' : [23,34,56,78],
    }
data11= { "emp_id2":[101,102,104,105,123],
         "salary2":[234,345,200,878,43],
         'house_nu':[345,345,345,56,234]
}

In [106]:
df10 = pd.DataFrame(data10,index = ['a','b','c','d'])

In [107]:
df11=pd.DataFrame(data11,index = ['a','b','d','e','f'])

In [108]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      878        56
f      123       43       234

In [109]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [110]:
df10.join(df11)   

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [113]:
df10.join(df11,how = 'right')  #join operation is done on row indexes and merge operation on column indexes

emp_id1  salary1    pf  emp_id2  salary2  house_nu
a    101.0    234.0  23.0      101      234       345
b    102.0    345.0  34.0      102      345       345
d    104.0    400.0  78.0      104      200       345
e      NaN      NaN   NaN      105      878        56
f      NaN      NaN   NaN      123       43       234

In [112]:
df10.join(df11,how = 'inner')

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23      101      234       345
b      102      345  34      102      345       345
d      104      400  78      104      200       345

In [119]:
df_sales = pd.read_csv(r'C:\Users\Prince\Downloads\sales_data_final.csv')

In [120]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [121]:
def profit_flag(a):
    if a>0:
        return 'positive'
    elif a<0:
        return 'negative'
    else:
        return 'no profit'

In [123]:
profit_flag(45)

'positive'

In [124]:
profit_flag(-78)

'negative'

In [126]:
df_sales['flag_profit'] = df_sales.profit.apply(profit_flag)  #apply function

In [127]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [128]:
def len_customer(a):
    return len(a)

In [129]:
df_sales['len_cust_name'] = df_sales['customer_name'].apply(len_customer) #df_sales['len_cust_name'] = df_sales['customer_name'].apply(len) 

In [130]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_cust_name  
0          35.46          Medium  2011     positive            15  
1           9.72          Medium  2011     positive            11  
2           8.17            High  2011     positive            13  
3           4.82            High  2011     negative            12  
4           4.70          Medium  2011     positive            11  

[5 rows x 23 columns]

In [131]:
df_sales['quantity'].unique()

array([ 2,  3,  4,  5,  1,  7,  6,  8,  9, 10, 11, 12, 14, 13],
      dtype=int64)

In [147]:
def quantity_flag(a):
    if a<10:
        return 'low'
    elif a>10 and a<20:
        return 'medium'
    elif a>=20:
        return 'high'

In [148]:
df_sales['flag_quantity']= df_sales['quantity'].apply(quantity_flag)

In [149]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     positive   
1        3      0.1   36.036          9.72          Medium  2011     positive   
2        4      0.0   29.640          8.17            High  2011     positive   
3        3      0.5  -26.055          4.82            High  2011     negative   
4        5      0.1   37.770          4.70          Medium  2011     positive   

   len_cust_name flag_quantity  
0             15           low  
1             11           low  
2             13           low  
3             12           low  
4             11           low  

[5 rows x 24 columns]

In [150]:
df_sales['flag_quantity'].unique()

array(['low', None, 'medium'], dtype=object)

In [151]:
df_sales['quantity'].unique()

array([ 2,  3,  4,  5,  1,  7,  6,  8,  9, 10, 11, 12, 14, 13],
      dtype=int64)

In [152]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda x:x**2)

In [153]:
df_sales.head(10)

order_id order_date ship_date       ship_mode     customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class   Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class       Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class     Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class      Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class       Joseph Holt   
5    IN-2011-47883   1/1/2011  1/8/2011  Standard Class       Joseph Holt   
6     CA-2011-1510   1/2/2011  1/6/2011  Standard Class   Magdelene Morse   
7    IN-2011-79397   1/3/2011  1/3/2011        Same Day       Kean Nguyen   
8    ID-2011-80230   1/3/2011  1/9/2011  Standard Class      Ken Lonsdale   
9     IZ-2011-4680   1/3/2011  1/7/2011  Standard Class  Lindsay Williams   

       segment            state      country  market   region  ... quantity  \
0     Consumer      Constantine      Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales    Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest      Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm       Sweden      EU    North  ...        3   
4     Consumer  New South Wales    Australia    APAC  Oceania  ...        5   
5     Consumer  New South Wales    Australia    APAC  Oceania  ...        2   
6     Consumer          Ontario       Canada  Canada   Canada  ...        1   
7    Corporate  New South Wales    Australia    APAC  Oceania  ...        1   
8     Consumer         Auckland  New Zealand    APAC  Oceania  ...        4   
9    Corporate           Ninawa         Iraq    EMEA     EMEA  ...        4   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     positive   
1      0.1   36.036          9.72         Medium  2011     positive   
2      0.0   29.640          8.17           High  2011     positive   
3      0.5  -26.055          4.82           High  2011     negative   
4      0.1   37.770          4.70         Medium  2011     positive   
5      0.1   15.342          1.80         Medium  2011     positive   
6      0.0    3.120         24.10         Medium  2011     positive   
7      0.1  110.412        125.32       Critical  2011     positive   
8      0.4 -319.464        107.10            Low  2011     negative   
9      0.0  253.320         81.26           High  2011     positive   

   len_cust_name  flag_quantity square_quantity  
0             15            low               4  
1             11            low               9  
2             13            low              16  
3             12            low               9  
4             11            low              25  
5             11            low               4  
6             15            low               1  
7             11            low               1  
8             12            low              16  
9             16            low              16  

[10 rows x 25 columns]

In [157]:
#Numpy numerical python 

In [158]:
import numpy as np

In [159]:
np.array([2,3,4,5,6])  #1D array

array([2, 3, 4, 5, 6])

In [160]:
type(np.array([2,3,4,5,6]))  #ndimensional array

numpy.ndarray

In [161]:
np.array([[2,3,4], [4,5,6]]) #2D array

array([[2, 3, 4],
       [4, 5, 6]])

In [162]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [163]:
l = [[1,2,3,4],[2,3,4,5]]

In [164]:
l[0][0]

1

In [168]:
a = np.array([3,4,5,6],ndmin = 3)

In [170]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [171]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
arr.ndim

2

In [175]:
arr1 = np.random.randint(1,10,(4,4))

array([[8, 3, 8, 4],
       [4, 2, 4, 6],
       [8, 3, 7, 9],
       [7, 6, 5, 8]])

In [179]:
np.random.randint(1,10,(4,4,2))

array([[[2, 1],
        [7, 3],
        [8, 8],
        [5, 4]],

       [[2, 4],
        [2, 9],
        [9, 8],
        [5, 7]],

       [[4, 1],
        [7, 1],
        [3, 1],
        [7, 3]],

       [[1, 5],
        [4, 6],
        [2, 8],
        [8, 4]]])

In [180]:
(np.random.randint(1,10,(4,4,2))).ndim

3

In [ ]:
# FITBIT
1. Read this dataset in pandas, mysql, and mongodb
2.while creating a table in mysql do not use manual approach to create it, always use a automation to create a table in mysql
##hint -use csvkit library to automate this task and to load a data in bulk in your mysql(import wizard)
3.convert all the dates available in dataset to timeformat in pandas and in mysql you have to convert it in date format
4.Find out in this data that how many unique id's you have 
5.which id is one of the active id that you have in whole dataset
6.how many of them have not logged there activity find out in terms of number of ids 
7.Find out who is laziest person id that we have in dataset
8.Explore over an internet that how much calories burn is required for a healthy person and find out how many healthy persons we have in our dataset
9.how many person are not a regular person with respect to activity try to find out those
10.who is the third most active person in this dataset find out those
11.who is the 5th most laziest person available in dataset and find it out
12.what is a total accumulative calories burn for a person and find out

In [ ]:
#task 2 -Superstore_USA
1.load this data in sql and in pandas with a relation in sql
2.while loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table 
3.Find out how many return that we have receied and with a product id
4.try to join order and return data both in sql and pandas
5.try to find out how many unique customer that we have
6.try to find out in how many regions we are selling a product and who is the manager of respective region
7.find out how many different shipment mode that we have and what is a percentage usability of all the segment
8.Create a new column and try to find out a difference between order date and shipment date
9. based on question number 8 find out for which order id we hvae shipment duration more than 10 days
10.try to find out a list of a returned order which shipment duration was more than 15 days and find out that region manager as well
11.Group by region and find out which region is more profitable 
12.Try to find out overall in which country we are giving more discount 
13.Give me a list of unique postal code 
14.which customer segment is more profitable find out
15.try to find out the 10the most loss making product category.
16.try to find out the product with most margins
17.try to find out 10 top product with highest margins
